CREATE DATABASE HOTEL_ALURA;

CREATE TABLE RESERVAS (ID INT AUTO_INCREMENT, DATA_ENTRADA DATE, DATA_SAIDA DATE, VALOR FLOAT, FORMA_PAGAMENTO VARCHAR(50), primary key (ID));

CREATE TABLE HOSPEDES (ID INT AUTO_INCREMENT, NOME VARCHAR(50), SOBRENOME VARCHAR(50), DATA_NASCIMENTO DATE, NACIONALIDADE VARCHAR(50), TELEFONE VARCHAR(50), primary key (ID));

ALTER TABLE HOSPEDES ADD COLUMN (ID_RESERVA INT);

ALTER TABLE HOSPEDES ADD foreign key (ID_RESERVA) references RESERVAS (ID);

CREATE TABLE USERS (ID INT AUTO_INCREMENT, LOGIN VARCHAR(50), SENHA VARCHAR(50), primary key (ID));

INSERT INTO USERS (LOGIN, SENHA) VALUES ('leonardolima', 'leolima12');
INSERT INTO USERS (LOGIN, SENHA) VALUES ('rosenildolero', 'rosenil24');
INSERT INTO USERS (LOGIN, SENHA) VALUES ('claudiamoraes', 'claumor32');